export type ProfileScreen =
  | 'home'
  | 'personal-info'
  | 'contact-details'
  | 'edit-mobile'
  | 'edit-email'
  | 'edit-address'
  | 'otp-verification'
  | 'contact-success'
  | 'kyc-details'
  | 'kyc-update'
  | 'kyc-review'
  | 'kyc-submitted'
  | 'accounts-preferences'
  | 'linked-accounts'
  | 'account-details'
  | 'set-primary'
  | 'default-debit'
  | 'account-nickname'
  | 'hide-account'
  | 'cards-payments'
  | 'default-card'
  | 'payment-preferences'
  | 'security-center'
  | 'change-password'
  | 'change-mpin'
  | 'biometric-settings'
  | 'transaction-auth'
  | 'login-activity'
  | 'devices-sessions'
  | 'trusted-devices'
  | 'active-sessions'
  | 'notifications'
  | 'privacy'
  | 'app-preferences'
  | 'documents'
  | 'help-support'
  | 'service-requests'
  | 'service-request-new'
  | 'service-request-details'
  | 'account-management'
  | 'account-closure'
  | 'account-closure-success'
  | 'logout-confirm';

export interface ProfileNavigation {
  screen: ProfileScreen;
  title: string;
  params?: Record<string, string>;
}
